version: '3.8'
services:

  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 1s
      retries: 20
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database-data:/var/lib/postgresql/data
  api:
    build: .
    container_name: todo_api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "start"]

volumes:
  database-data: