version: '3.8'
services:

  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 10

  alembic:
    image: python:3.11
    working_dir: /app
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "pip install alembic sqlalchemy psycopg2-binary && alembic upgrade head"

  api:
    build: .
    container_name: todo_api
    depends_on:
      db:
        condition: service_healthy
      alembic:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]

volumes:
  database-data:
